default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: passwordadmin
  host: db
  timeout: 5000
 
development:
  <<: *default
  database: development_mydb
 

test:
  <<: *default
  database: test_mydb
 

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
